name: Admin Panel CI/CD

on:
  push:
    branches: [main]
    paths:
      - "apps/admin-panel/**"
      - "shared/**"
  pull_request:
    branches: [main]
    paths:
      - "apps/admin-panel/**"
      - "shared/**"

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build shared library
        run: npm run build:shared

      - name: Build admin panel
        run: npm run build:admin

      - name: Run tests
        run: npm run test -- --project=admin-panel

      - name: Run linting
        run: npm run lint -- --project=admin-panel

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/admin-panel/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/admin-panel:latest
